tools:
  external_code_coverage: true

checks:
  php:
    code_rating: true
    duplication: true
build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override: [ php-scrutinizer-run ]
